FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
COPY tsconfig.json ./
# ENV NODE_ENV: development
# ENV DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
# ENV PROTOCOL_BASE_URL: ${PROTOCOL_BASE_URL}
# ENV SSE_TIMEOUT: ${SSE_TIMEOUT}
# ENV DOMAIN: ${DOMAIN}
# ENV COUNTRY: ${COUNTRY}
# ENV BAP_ID: ${BAP_ID}
# ENV EXPECTED_RESPONSE_TIME: ${EXPECTED_RESPONSE_TIME}
# ENV EXPECTED_RESOLUTION_TIME: ${EXPECTED_RESOLUTION_TIME}
# ENV BUGZILLA_API_KEY: ${BUGZILLA_API_KEY}
# ENV BAP_URL: ${BAP_URL}
COPY . .
RUN npm install --development
RUN npm run build
CMD [ "node", "dist/index.js" ]
